name: Build and Deploy Air Traffic Control

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 for building the project
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean package

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.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 }}  # Use your token secret
          publish_dir: ./target  # Publish from the target directory
