name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.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 }}
          publish_dir: ./target  # Adjust this to your output directory
