name: Deploy Air Traffic Control to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify the Java version
          distribution: 'adopt'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean package  # Build the project

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Action for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.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 }}  # Use the GitHub token to authenticate
          publish_dir: ./target  # Specify the directory to publish (output directory from Maven)
